/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controlador.ControladorCliente;

import DAO.ClienteDAO;
import DAO.ConexaoDAO;
import Persistencia.Cliente;
import br.com.caelum.stella.validation.CPFValidator;
import br.com.caelum.stella.validation.InvalidStateException;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import util.EnviaEmail;
import util.TeclasPermetidas;

import util.ValidarCPF;
import util.ValidaStrings;
/**
 *
 * @author victor
 */
public class ClienteGUI extends javax.swing.JFrame {
    Cliente cli = new Cliente();
    ControladorCliente contr = new ControladorCliente();
    ConexaoDAO conn = new ConexaoDAO();
    ClienteDAO CD = new ClienteDAO();
    
    public void ativaCampos (){
       
        TxtEmail.enable(true);
        TxtNome.enable(true);
        TxtCpf.enable(true);
        TxtRg.enable(true);
        TxtTel.enable(true);
    }
    public void limpaCampos (){
        TxtCodigo.setText(null);
        TxtEmail.setText(null);
        TxtNome.setText(null);
        TxtCpf.setText(null);
        TxtRg.setText(null);
        TxtTel.setText(null);
    }
    
    public ClienteGUI() {
        initComponents();
        TxtNome.setDocument(new TeclasPermetidas());
        TxtCodigo.enable(false);
        TxtEmail.enable(false);
        TxtNome.enable(false);
        TxtCpf.enable(false);
        TxtRg.enable(false);
        TxtTel.enable(false);
         TabelaCarros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
          try {
        conn.conecta();
        ResultSet rs = contr.listaCliente();
        DefaultTableModel modelo =  CD.carregarTabela(rs);
        TabelaCarros.setModel(modelo);
        TabelaCarros.setSelectionBackground(Color.yellow);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Erro:");
        }
           try {
        conn.conecta();
        ResultSet rs = contr.listaCliente();
        DefaultTableModel modelo =  CD.carregarTabela(rs);
        TabelaCarros1.setModel(modelo);
        TabelaCarros1.setSelectionBackground(Color.yellow);
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Erro:");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        btnCadastra = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbm_filtra = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TxtPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaCarros = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TxtAnexo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtEmail1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtNomeEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbm_filtra1 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        TxtPesquisar1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaCarros1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Codigo:");

        TxtCodigo.setEnabled(false);

        jLabel2.setText("Nome:");

        TxtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNomeKeyPressed(evt);
            }
        });

        jLabel3.setText("Email:");

        jLabel4.setText("RG:");

        try {
            TxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("CPF:");

        try {
            TxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TxtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCpfKeyPressed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        try {
            TxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton4.setText("Novo");
        jButton4.setMaximumSize(new java.awt.Dimension(75, 29));
        jButton4.setMinimumSize(new java.awt.Dimension(75, 29));
        jButton4.setPreferredSize(new java.awt.Dimension(75, 29));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnCadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        btnCadastra.setText("Cadastrar");
        btnCadastra.setEnabled(false);
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_page.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pesquisar cliente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Filtra por:");

        cbm_filtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPF", "Nome", "RG" }));

        jLabel9.setText("=");

        TxtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisarActionPerformed(evt);
            }
        });
        TxtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyReleased(evt);
            }
        });

        TabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCarrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaCarros);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(2, 2, 2)
                                .addComponent(TxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(3, 3, 3)
                                .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastra)
                        .addGap(5, 5, 5)
                        .addComponent(btnAlterar)
                        .addGap(7, 7, 7)
                        .addComponent(btnDeletar))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastra)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlterar)
                    .addComponent(btnDeletar))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manuntenção", new javax.swing.ImageIcon(getClass().getResource("/Imagens/process.png")), jPanel1); // NOI18N

        jLabel7.setText("Url Anexo:");

        TxtAnexo.setEnabled(false);

        jLabel10.setText("Email:");

        TxtEmail1.setEnabled(false);

        jLabel11.setText("Nome:");

        TxtNomeEmail.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pesquisar cliente:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setText("Filtra por:");

        cbm_filtra1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPF", "Nome", "RG" }));

        jLabel13.setText("=");

        TxtPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisar1ActionPerformed(evt);
            }
        });
        TxtPesquisar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisar1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisar1KeyReleased(evt);
            }
        });

        TabelaCarros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaCarros1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCarros1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaCarros1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbm_filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbm_filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(TxtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtAnexo)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(TxtNomeEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TxtAnexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TxtNomeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TxtEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(10, 10, 10)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Promoções", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       btnCadastra.setEnabled(true);
       btnAlterar.setEnabled(false);
       btnDeletar.setEnabled(false);
        ativaCampos();
        limpaCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
               cli.setEmail(TxtEmail.getText());
                cli.setCpf(TxtCpf.getText());
                cli.setNome(TxtNome.getText());
                cli.setRg(TxtRg.getText());
                cli.setTelefone(TxtTel.getText());
      if((CD.achanome(cli)==true)||(CD.achaCPF(cli)==true)||(CD.achaRG(cli)==true)){
          JOptionPane.showMessageDialog(null, "Dados existentes");
      }
      
      else{
    try {
       String Cpf1 = TxtCpf.getText().replace(".", "");
       String CPF = Cpf1.replace("-", "");
       String Nome = TxtNome.getText();
       
        if (ValidaStrings.isNome(Nome)==true){
        if(ValidarCPF.isCPF(CPF)==true){
         
        if ((TxtCpf.getText().isEmpty())||TxtEmail.getText().isEmpty()||(TxtNome.getText().isEmpty()||(TxtRg.getText().isEmpty()||TxtTel.getText().isEmpty())))
        {
            JOptionPane.showMessageDialog(null, "Existem campos em branco");

        }

        else{

           
             
                
                
                cli.setEmail(TxtEmail.getText());
                cli.setCpf(TxtCpf.getText());
                cli.setNome(TxtNome.getText());
                cli.setRg(TxtRg.getText());
                cli.setTelefone(TxtTel.getText());
               
                int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja cadastra");

                if (resposta == 0){
                    contr.incluirCliente(cli);
                    
                    conn.conecta();
                    limpaCampos();
                    ResultSet rs = contr.listaCliente();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);

                }
              
            }
        }
       
        else {
            JOptionPane.showMessageDialog(null,"CPF INVALIDO");
        }
        }
        else {
            JOptionPane.showMessageDialog(null,"Digite nome valido");
            TxtNome.setFocusable(true);
        }
    }
              
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro No banco:"+ex);

            }
          
            // JOptionPane.showMessageDialog(null, "Modelo"+ca.getModelo()+"\n Nome:"+ca.getNome()+"\n Ano:"+ca.getAno()+"\n Cor:"+ca.getCor()+"\n Valor:"+ca.getValor()+"\n Pacote:"+ca.getPacote());
    
      }
    
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        String Cpf1 = TxtCpf.getText().replace(".", "");
       String CPF = Cpf1.replace("-", "");
        
        if(ValidarCPF.isCPF(CPF)==true){
            
        try {
            
            cli.setCodCliente(Integer.parseInt(TxtCodigo.getText()));
                cli.setEmail(TxtEmail.getText());
                cli.setCpf(TxtCpf.getText());
                cli.setNome(TxtNome.getText());
                cli.setRg(TxtRg.getText());
                cli.setTelefone(TxtTel.getText());

            int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja alterar o registro");

            if (resposta == 0){
                contr.alterarCliente(cli);
                limpaCampos();
                try {
                    conn.conecta();
                    ResultSet rs = contr.listaCliente();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro:");
                }

            }
            }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
      }
        else {
             JOptionPane.showMessageDialog(null,"CPF INVALIDO");
        }       
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        cli.setCodCliente(Integer.parseInt(TxtCodigo.getText()));

        int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja excluir");

        if (resposta == 0){
            contr.excluirCliente(cli);
            limpaCampos();

            try {
                conn.conecta();
                ResultSet rs = contr.listaCliente();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaCarros.setModel(modelo);
                TabelaCarros.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void TxtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisarActionPerformed

    }//GEN-LAST:event_TxtPesquisarActionPerformed

    private void TxtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyPressed

    }//GEN-LAST:event_TxtPesquisarKeyPressed

    private void TxtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyReleased
        if(TxtPesquisar.getText().isEmpty()){
            try {
                conn.conecta();
                ResultSet rs = contr.listaCliente();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaCarros.setModel(modelo);
                TabelaCarros.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }

        else{
            if (cbm_filtra.getSelectedIndex()==0){
                try {
                    cli.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }

            if (cbm_filtra.getSelectedIndex()==1){
                try {
                    cli.setNome(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarNomeCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }
            
            if (cbm_filtra.getSelectedIndex()==2){
                try {
                    cli.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_TxtPesquisarKeyReleased

    private void TabelaCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCarrosMouseClicked
        try{
            int linha = TabelaCarros.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Linhas:"+ linha);
            Object objCodigo = TabelaCarros.getValueAt(linha, 0);
            Object objemail = TabelaCarros.getValueAt(linha, 1);
            Object objrg = TabelaCarros.getValueAt(linha,2);
            Object objnome = TabelaCarros.getValueAt(linha,3);
            Object objtel = TabelaCarros.getValueAt(linha,4);
            Object objCpf = TabelaCarros.getValueAt(linha,5);
            ativaCampos();
            btnCadastra.setEnabled(false);
       btnAlterar.setEnabled(true);
       btnDeletar.setEnabled(true);
            

            TxtCodigo.setText(objCodigo.toString());
            TxtCpf.setText(objCpf.toString());
            TxtEmail.setText(objemail.toString());
            TxtNome.setText(objnome.toString());
            TxtRg.setText(objrg.toString());
            TxtTel.setText(objtel.toString());
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os dados"+e.getMessage());
        }
    }//GEN-LAST:event_TabelaCarrosMouseClicked

    private void TxtCpfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCpfKeyPressed
           
    }//GEN-LAST:event_TxtCpfKeyPressed

    private void TxtPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisar1ActionPerformed

    private void TxtPesquisar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisar1KeyPressed
  if(TxtPesquisar.getText().isEmpty()){
            try {
                conn.conecta();
                ResultSet rs = contr.listaCliente();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaCarros1.setModel(modelo);
                TabelaCarros1.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro");
            }
        }

        else{
            if (cbm_filtra.getSelectedIndex()==0){
                try {
                    cli.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros1.setModel(modelo);
                    TabelaCarros1.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }

            if (cbm_filtra.getSelectedIndex()==1){
                try {
                    cli.setNome(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarNomeCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros1.setModel(modelo);
                    TabelaCarros1.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }
            
            if (cbm_filtra.getSelectedIndex()==2){
                try {
                    cli.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfCliente(cli);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros1.setModel(modelo);
                    TabelaCarros1.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao Buscar Dados:"+ex.getMessage());
                }
            }
        }       
    }//GEN-LAST:event_TxtPesquisar1KeyPressed

    private void TxtPesquisar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisar1KeyReleased

    private void TabelaCarros1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCarros1MouseClicked
         try{
            int linha = TabelaCarros1.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Linhas:"+ linha);
            Object objCodigo = TabelaCarros1.getValueAt(linha, 0);
            Object objemail = TabelaCarros1.getValueAt(linha, 1);
            Object objrg = TabelaCarros1.getValueAt(linha,2);
            Object objnome = TabelaCarros1.getValueAt(linha,3);
            Object objtel = TabelaCarros1.getValueAt(linha,4);
            Object objCpf = TabelaCarros1.getValueAt(linha,5);
            
            TxtEmail1.setText(objemail.toString());
            TxtNomeEmail.setText(objnome.toString());
            TxtAnexo.setEnabled(true);
        
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os dados"+e.getMessage());
        }
    }//GEN-LAST:event_TabelaCarros1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
        EnviaEmail enviar = new EnviaEmail();
      String emailUser = TxtEmail1.getText();
      String nome = TxtNomeEmail.getText();
      String URL = TxtAnexo.getText();
      enviar.EnviaMensage(emailUser, nome, URL);
       }
       catch(Exception ex ){
           JOptionPane.showMessageDialog(null,"Erro ao enviar o email"+ ex);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TxtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNomeKeyPressed
        
        
    }//GEN-LAST:event_TxtNomeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      try {              
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());   
                 } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ClienteGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaCarros;
    private javax.swing.JTable TabelaCarros1;
    private javax.swing.JTextField TxtAnexo;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JFormattedTextField TxtCpf;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtEmail1;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNomeEmail;
    private javax.swing.JTextField TxtPesquisar;
    private javax.swing.JTextField TxtPesquisar1;
    private javax.swing.JFormattedTextField TxtRg;
    private javax.swing.JFormattedTextField TxtTel;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JComboBox cbm_filtra;
    private javax.swing.JComboBox cbm_filtra1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
