

package Visão;

import Controlador.ControladorFuncionario;
import Controlador.ControladorLogin;
import DAO.ConexaoDAO;
import DAO.FuncionarioDAO;
import DAO.LoginDAO;
import Persistencia.Funcionario;
import Persistencia.Login;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import util.ValidarCPF;

/**
 *
 * @author victor
 */
public class FuncionarioGUI extends javax.swing.JFrame {

    Funcionario fun = new Funcionario();
    ControladorFuncionario contr = new ControladorFuncionario();
    ConexaoDAO conn = new ConexaoDAO();
    FuncionarioDAO CD = new FuncionarioDAO();
    LoginDAO LD = new LoginDAO();
    Login lo = new Login();
    ControladorLogin contr_login = new ControladorLogin();
    
    
    public void ativaCampos (){
       
     
        TxtNome.enable(true);
        TxtCpf.enable(true);
        TxtRg.enable(true);
        TxtTel.enable(true);
        TxtLogradouro.enable(true);
        TxtNumero.enable(true);
        TxtBairro.enable(true);
        //txtSenha.enable(true);
        //TxtUser.enable(true);
    }
    public void limpaCampos (){
        TxtCodigo.setText("");
       
      
        TxtNome.setText("");
        TxtCpf.setText("");
        TxtRg.setText("");
        TxtTel.setText("");
        TxtBairro.setText("");
        TxtSenha.setVisible(false);
        TxtUsuario.setVisible(false);
        TxtLogradouro.setText("");
        TxtNumero.setText("");
        TxtBairro.setText("");
        
    }
    
    
    public FuncionarioGUI() {
        initComponents();
        
        TxtSenha.setVisible(false);
        TxtUsuario.setVisible(false);
        TxtNome.enable(false);
        TxtCpf.enable(false);
        TxtRg.enable(false);
        TxtTel.enable(false);
        TxtLogradouro.enable(false);
        TxtNumero.enable(false);
        TxtBairro.enable(false);
        TabelaFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
         
            try {
                conn.conecta();
                ResultSet rs = contr.listaFuncionario();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaFuncionarios.setModel(modelo);
                TabelaFuncionarios.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
              try {
                conn.conecta();
                ResultSet rs = contr_login.listaLogin();
                DefaultTableModel modelo =  LD.carregarTabela(rs);
                TabelaFuncionarios1.setModel(modelo);
                TabelaFuncionarios1.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
            

        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField4 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblcodigo = new javax.swing.JLabel();
        TxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtRg = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtTel = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        btnCadastraFuncionario = new javax.swing.JButton();
        btnAlterarFuncionario = new javax.swing.JButton();
        btnExcluirFuncionario = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbm_filtra = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TxtPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaFuncionarios = new javax.swing.JTable();
        lblcargo = new javax.swing.JLabel();
        jrbmasculino = new javax.swing.JRadioButton();
        jrbfeminino = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtLogradouro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbm_cargo = new javax.swing.JComboBox();
        TxtSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        TxtUsuario1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TxtSenha1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbm_filtra1 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        TxtPesquisar1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaFuncionarios1 = new javax.swing.JTable();
        btnAlterarLogin = new javax.swing.JButton();
        btnExcluirLogin = new javax.swing.JButton();
        lblcodigo1 = new javax.swing.JLabel();
        txtCodLog = new javax.swing.JTextField();
        btnGerarCodigo = new javax.swing.JButton();
        txtCodBarra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        jTextField4.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        lblcodigo.setText("Codigo:");

        TxtCodigo.setEditable(false);
        TxtCodigo.setEnabled(false);

        jLabel2.setText("Nome:");

        jLabel4.setText("RG:");

        try {
            TxtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("CPF:");

        try {
            TxtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Telefone:");

        try {
            TxtTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton4.setText("Novo");
        jButton4.setMaximumSize(new java.awt.Dimension(75, 29));
        jButton4.setMinimumSize(new java.awt.Dimension(75, 29));
        jButton4.setPreferredSize(new java.awt.Dimension(75, 29));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnCadastraFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        btnCadastraFuncionario.setText("Cadastrar");
        btnCadastraFuncionario.setEnabled(false);
        btnCadastraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraFuncionarioActionPerformed(evt);
            }
        });

        btnAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh.png"))); // NOI18N
        btnAlterarFuncionario.setText("Alterar");
        btnAlterarFuncionario.setEnabled(false);
        btnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFuncionarioActionPerformed(evt);
            }
        });

        btnExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_page.png"))); // NOI18N
        btnExcluirFuncionario.setText("Deletar");
        btnExcluirFuncionario.setEnabled(false);
        btnExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirFuncionarioActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pesquisar funcionario:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Filtra por:");

        cbm_filtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CPF", "Nome", "RG" }));

        jLabel9.setText("=");

        TxtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisarActionPerformed(evt);
            }
        });
        TxtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyReleased(evt);
            }
        });

        TabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaFuncionarios);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblcargo.setText("Cargo:");

        buttonGroup1.add(jrbmasculino);
        jrbmasculino.setText("Masculino");

        buttonGroup1.add(jrbfeminino);
        jrbfeminino.setText("Feminino");

        jLabel1.setText("Sexo:");

        jLabel3.setText("Rua:");

        jLabel7.setText("Numero:");

        jLabel10.setText("Bairro:");

        jLabel11.setText("Usuario:");

        jLabel12.setText("Senha:");

        cbm_cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente", "Funcionario" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel1)
                                    .addGap(3, 3, 3)
                                    .addComponent(jrbmasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrbfeminino))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCadastraFuncionario)
                                    .addGap(5, 5, 5)
                                    .addComponent(btnAlterarFuncionario)
                                    .addGap(7, 7, 7)
                                    .addComponent(btnExcluirFuncionario)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblcodigo)
                                    .addGap(4, 4, 4)
                                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblcargo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbm_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TxtUsuario))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(40, 40, 40)
                                    .addComponent(jLabel4)
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel3)
                                    .addGap(4, 4, 4)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addGap(4, 4, 4)
                                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel5))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TxtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel7)
                                    .addGap(2, 2, 2)
                                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10))
                                .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtBairro)
                                .addComponent(TxtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcargo)
                    .addComponent(jLabel11)
                    .addComponent(TxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbm_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jrbmasculino)
                    .addComponent(jrbfeminino)
                    .addComponent(jLabel1)
                    .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastraFuncionario)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlterarFuncionario)
                    .addComponent(btnExcluirFuncionario))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manuntenção", new javax.swing.ImageIcon(getClass().getResource("/Imagens/process.png")), jPanel1); // NOI18N

        jLabel13.setText("Usuario:");

        jLabel14.setText("Senha:");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pesquisar Usuarios:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel15.setText("Filtra por:");

        cbm_filtra1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuario", " " }));

        jLabel16.setText("=");

        TxtPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisar1ActionPerformed(evt);
            }
        });
        TxtPesquisar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisar1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisar1KeyReleased(evt);
            }
        });

        TabelaFuncionarios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelaFuncionarios1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaFuncionarios1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TabelaFuncionarios1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbm_filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbm_filtra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TxtPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAlterarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh.png"))); // NOI18N
        btnAlterarLogin.setText("Alterar");
        btnAlterarLogin.setEnabled(false);
        btnAlterarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarLoginActionPerformed(evt);
            }
        });

        btnExcluirLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_page.png"))); // NOI18N
        btnExcluirLogin.setText("Deletar");
        btnExcluirLogin.setEnabled(false);
        btnExcluirLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLoginActionPerformed(evt);
            }
        });

        lblcodigo1.setText("Codigo:");

        txtCodLog.setEditable(false);

        btnGerarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder.png"))); // NOI18N
        btnGerarCodigo.setText("Gerar Cartão");
        btnGerarCodigo.setEnabled(false);
        btnGerarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarCodigoActionPerformed(evt);
            }
        });

        jLabel17.setText("Codigo Barra");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnAlterarLogin)
                                .addGap(7, 7, 7)
                                .addComponent(btnExcluirLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGerarCodigo)))
                        .addContainerGap(78, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblcodigo1)
                            .addComponent(jLabel17))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodBarra)
                            .addComponent(txtCodLog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TxtUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(TxtSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcodigo1)
                    .addComponent(txtCodLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarLogin)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnExcluirLogin)
                        .addComponent(btnGerarCodigo)))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro Cartão", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         btnCadastraFuncionario.setEnabled(true);
         btnAlterarFuncionario.setEnabled(false);
         btnExcluirFuncionario.setEnabled(false);
        ativaCampos();
        limpaCampos();
        TxtSenha.setVisible(true);
        TxtUsuario.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCadastraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraFuncionarioActionPerformed
        String Cpf1 = TxtCpf.getText().replace(".", "");
       String CPF = Cpf1.replace("-", "");
        
        if(ValidarCPF.isCPF(CPF)==true){ 
        fun.setCpf(TxtCpf.getText());
                fun.setNome(TxtNome.getText());
                fun.setRg(TxtRg.getText());
        if ((CD.achaCPF(fun)==true)||(CD.achaNome(fun)==true)||(CD.achaRG(fun)==true)){
          JOptionPane.showMessageDialog(null, "Dados existentes");
        }        
        else { 
        if ((TxtCpf.getText().isEmpty())||(TxtNome.getText().isEmpty()||(TxtRg.getText().isEmpty()||(TxtTel.getText().isEmpty()||(TxtLogradouro.getText().isEmpty()||(TxtNumero.getText().isEmpty()||(TxtBairro.getText().isEmpty())))))))
        {
            JOptionPane.showMessageDialog(null, "Existem campos em branco");

        }

        else{

            
            try {
                lo.setNivel_acesso((String) cbm_cargo.getSelectedItem());
                lo.setSenha(TxtSenha.getText());
                lo.setUsuario(TxtUsuario.getText());
                lo.setCod_barra(Long.parseLong(CPF));
                fun.setCargo((String) cbm_cargo.getSelectedItem());
                fun.setCpf(TxtCpf.getText());
                fun.setNome(TxtNome.getText());
                fun.setRg(TxtRg.getText());
                fun.setTelefone(TxtTel.getText());
                fun.setLogradouro(TxtLogradouro.getText());
                fun.setNumero(TxtNumero.getText());
                fun.setBairro(TxtBairro.getText());
                
                if (jrbmasculino.getModel().isSelected())
                {
                    fun.setSexo(jrbmasculino.getText());
                }
                else if (jrbfeminino.getModel().isSelected())
                {
                    fun.setSexo(jrbfeminino.getText());
                }
                int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja cadastrar");
                
                if (resposta == 0){
                    contr.incluirFuncionario(fun);
                    contr_login.incluirLogin(lo);
                    conn.conecta();
                    limpaCampos();
                    ResultSet rs = contr.listaFuncionario();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaFuncionarios.setModel(modelo);

                }
                
               
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro No banco:"+ex);

            }

            // JOptionPane.showMessageDialog(null, "Modelo"+ca.getModelo()+"\n Nome:"+ca.getNome()+"\n Ano:"+ca.getAno()+"\n Cor:"+ca.getCor()+"\n Valor:"+ca.getValor()+"\n Pacote:"+ca.getPacote());

        }
        }
        }
        else{
            JOptionPane.showMessageDialog(null,"CPF INVALIDO");
        }
    }//GEN-LAST:event_btnCadastraFuncionarioActionPerformed

    private void btnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFuncionarioActionPerformed
fun.setCpf(TxtCpf.getText());
                fun.setNome(TxtNome.getText());
                fun.setRg(TxtRg.getText());
        if ((CD.achaCPF(fun)==true)||(CD.achaNome(fun)==true)||(CD.achaRG(fun)==true)){
          JOptionPane.showMessageDialog(null, "Dados existentes");
        }  
        else {
        
        String Cpf1 = TxtCpf.getText().replace(".", "");
       String CPF = Cpf1.replace("-", "");
        
        if(ValidarCPF.isCPF(CPF)==true){
        try {

            fun.setCodFuncionario(Integer.parseInt(TxtCodigo.getText()));
            fun.setCargo((String) cbm_cargo.getSelectedItem());
            fun.setCpf(TxtCpf.getText());
            fun.setNome(TxtNome.getText());
            fun.setRg(TxtRg.getText());
            fun.setTelefone(TxtTel.getText());
              if (jrbmasculino.getModel().isSelected())
                {
                    fun.setSexo(jrbmasculino.getText());
                }
                else if (jrbfeminino.getModel().isSelected())
                {
                    fun.setSexo(jrbfeminino.getText());
                }

            int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja alterar o registro");

            if (resposta == 0){
                contr.alterarFuncionario(fun);
                limpaCampos();
                try {
                    conn.conecta();
                    ResultSet rs = contr.listaFuncionario();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaFuncionarios.setModel(modelo);
                    TabelaFuncionarios.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro:");
                }

            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }
        else {
            JOptionPane.showMessageDialog(null, "CPF INVALIDO");
        }
       }
    }//GEN-LAST:event_btnAlterarFuncionarioActionPerformed

    private void btnExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFuncionarioActionPerformed

        fun.setCodFuncionario(Integer.parseInt(TxtCodigo.getText()));

        int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja excluir");

        if (resposta == 0){
            contr.excluirFuncionario(fun);
            limpaCampos();

            try {
                conn.conecta();
                ResultSet rs = contr.listaFuncionario();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaFuncionarios.setModel(modelo);
                TabelaFuncionarios.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
        }
    }//GEN-LAST:event_btnExcluirFuncionarioActionPerformed

    private void TxtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisarActionPerformed

    }//GEN-LAST:event_TxtPesquisarActionPerformed

    private void TxtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyPressed

    }//GEN-LAST:event_TxtPesquisarKeyPressed

    private void TxtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyReleased
        if(TxtPesquisar.getText().isEmpty()){
            try {
                conn.conecta();
                ResultSet rs = contr.listaFuncionario();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaFuncionarios.setModel(modelo);
                TabelaFuncionarios.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
        }

        else{
            if (cbm_filtra.getSelectedIndex()==0){
                try {
                    fun.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfFuncionario(fun);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaFuncionarios.setModel(modelo);
                    TabelaFuncionarios.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao buscar dados:"+ex.getMessage());
                }
            }

            if (cbm_filtra.getSelectedIndex()==1){
                try {
                    fun.setNome(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarNomeFuncionario(fun);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaFuncionarios.setModel(modelo);
                    TabelaFuncionarios.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao buscar dados:"+ex.getMessage());
                }
            }

            if (cbm_filtra.getSelectedIndex()==2){
                try {
                    fun.setCpf(TxtPesquisar.getText());
                    conn.conecta();
                    ResultSet rs = contr.buscarCpfFuncionario(fun);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaFuncionarios.setModel(modelo);
                    TabelaFuncionarios.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao buscar dados:"+ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_TxtPesquisarKeyReleased

    private void TabelaFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFuncionariosMouseClicked
        try{
            int linha = TabelaFuncionarios.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Linhas:"+ linha);
            Object objCodigo = TabelaFuncionarios.getValueAt(linha, 0);
            Object objemail = TabelaFuncionarios.getValueAt(linha, 1);
            Object objrg = TabelaFuncionarios.getValueAt(linha,2);
            Object objnome = TabelaFuncionarios.getValueAt(linha,3);
            Object objtel = TabelaFuncionarios.getValueAt(linha,4);
            Object objCpf = TabelaFuncionarios.getValueAt(linha,5);
            ativaCampos();
            btnCadastraFuncionario.setEnabled(false);
            btnAlterarFuncionario.setEnabled(true);
            btnExcluirFuncionario.setEnabled(true);

            TxtCodigo.setText(objCodigo.toString());
            TxtCpf.setText(objCpf.toString());
            cbm_cargo.setSelectedItem(objemail.toString());
            TxtNome.setText(objnome.toString());
            TxtRg.setText(objrg.toString());
            TxtTel.setText(objtel.toString());
            TxtSenha.setVisible(false);
        TxtUsuario.setVisible(false);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os dados"+e.getMessage());
        }
    }//GEN-LAST:event_TabelaFuncionariosMouseClicked

    private void TxtPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisar1ActionPerformed

    private void TxtPesquisar1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisar1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisar1KeyPressed

    private void TxtPesquisar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPesquisar1KeyReleased

    private void TabelaFuncionarios1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaFuncionarios1MouseClicked
         int linha = TabelaFuncionarios1.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Linhas:"+ linha);
            Object objCodigo = TabelaFuncionarios1.getValueAt(linha, 0);
            Object objusuario = TabelaFuncionarios1.getValueAt(linha, 1);
            Object objSenha = TabelaFuncionarios1.getValueAt(linha,2);
            Object objCodBarra = TabelaFuncionarios1.getValueAt(linha, 4);
            
            txtCodLog.setText(objCodigo.toString());
            TxtUsuario1.setText(objusuario.toString());
            TxtSenha1.setText(objSenha.toString());
            txtCodBarra.setText(objCodBarra.toString());
            btnGerarCodigo.setEnabled(true);
            btnAlterarLogin.setEnabled(true);
            btnExcluirLogin.setEnabled(true);
    }//GEN-LAST:event_TabelaFuncionarios1MouseClicked

    private void btnAlterarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarLoginActionPerformed
         lo.setCodLogin(Integer.parseInt(txtCodLog.getText()));
        lo.setUsuario(TxtUsuario1.getText());
        lo.setSenha(TxtSenha1.getText());
        lo.setCod_barra(Long.parseLong(txtCodBarra.getText()));
        contr_login.alterarLogin(lo);
        try {
                conn.conecta();
                ResultSet rs = contr_login.listaLogin();
                DefaultTableModel modelo =  LD.carregarTabela(rs);
                TabelaFuncionarios1.setModel(modelo);
                TabelaFuncionarios1.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
            
    }//GEN-LAST:event_btnAlterarLoginActionPerformed

    private void btnExcluirLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLoginActionPerformed
        try {
                conn.conecta();
                ResultSet rs = contr_login.listaLogin();
                DefaultTableModel modelo =  LD.carregarTabela(rs);
                TabelaFuncionarios1.setModel(modelo);
                TabelaFuncionarios1.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
            
    }//GEN-LAST:event_btnExcluirLoginActionPerformed

    private void btnGerarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarCodigoActionPerformed
        LD.GerarCodigoBarra(txtCodBarra);
    }//GEN-LAST:event_btnGerarCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuncionarioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuncionarioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaFuncionarios;
    private javax.swing.JTable TabelaFuncionarios1;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCodigo;
    private javax.swing.JFormattedTextField TxtCpf;
    private javax.swing.JTextField TxtLogradouro;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtPesquisar;
    private javax.swing.JTextField TxtPesquisar1;
    private javax.swing.JFormattedTextField TxtRg;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JTextField TxtSenha1;
    private javax.swing.JFormattedTextField TxtTel;
    private javax.swing.JTextField TxtUsuario;
    private javax.swing.JTextField TxtUsuario1;
    private javax.swing.JButton btnAlterarFuncionario;
    private javax.swing.JButton btnAlterarLogin;
    private javax.swing.JButton btnCadastraFuncionario;
    private javax.swing.JButton btnExcluirFuncionario;
    private javax.swing.JButton btnExcluirLogin;
    private javax.swing.JButton btnGerarCodigo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbm_cargo;
    private javax.swing.JComboBox cbm_filtra;
    private javax.swing.JComboBox cbm_filtra1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JRadioButton jrbfeminino;
    private javax.swing.JRadioButton jrbmasculino;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcodigo1;
    private javax.swing.JTextField txtCodBarra;
    private javax.swing.JTextField txtCodLog;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
