/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controlador.ControladorLogin;

import DAO.ConexaoDAO;
import DAO.LoginDAO;
import Persistencia.Login;
import com.l2fprod.gui.plaf.skin.SkinLookAndFeel;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author victor
 */
public class LoginGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
     ControladorLogin contr = new ControladorLogin();
     ConexaoDAO conn = new ConexaoDAO();
     LoginDAO loginDAO = new LoginDAO();
     Login lo = new Login();
     MenuGUI  menugui;
    
    public LoginGUI() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
       //jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));  
        //jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        CmbNivelAcesso = new javax.swing.JComboBox();
        btnEntra = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        TxtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11983_64x64.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 70, 64, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7586_64x64.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 136, 60, 64);

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        TxtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtUserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtUserKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtUserKeyTyped(evt);
            }
        });
        jPanel1.add(TxtUser);
        TxtUser.setBounds(120, 90, 280, 40);

        CmbNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Gerente", "Funcionario", " " }));
        CmbNivelAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbNivelAcessoActionPerformed(evt);
            }
        });
        jPanel1.add(CmbNivelAcesso);
        CmbNivelAcesso.setBounds(120, 210, 280, 40);

        btnEntra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        btnEntra.setText("Entrar");
        btnEntra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntraActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntra);
        btnEntra.setBounds(120, 310, 110, 40);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/block.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel1.add(btnSair);
        btnSair.setBounds(290, 310, 110, 40);
        jPanel1.add(TxtSenha);
        TxtSenha.setBounds(120, 150, 280, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(410, 200, 510, 370);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pizza-Cuadrada_Mesa_Fondos-HD-de-Comidas.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1570, 980);

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CmbNivelAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbNivelAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CmbNivelAcessoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEntraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntraActionPerformed
       try {
           if((TxtSenha.getText().isEmpty())||((TxtUser.getText().isEmpty()))){
          JOptionPane.showMessageDialog(null,"Existe campos em branco");
           }    
           else{
           
           lo.setUsuario(TxtUser.getText());
           lo.setSenha(TxtSenha.getText());
           lo.setNivel_acesso((String) CmbNivelAcesso.getSelectedItem());
         
         

           contr.AcessarSistema(lo);
           
          
          }
       }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Erro de formulario"+ ex.getMessage());
        }
    }//GEN-LAST:event_btnEntraActionPerformed

    private void TxtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUserKeyPressed
        
        Connection dbcon = null;
      //instanciando um objeto a partir da classe ConexaoDAO
      ConexaoDAO conecta = new ConexaoDAO();
      Statement st;
      ResultSet rs;
              
        
        
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         try{
             
         dbcon = conecta.obterConexao();
         st = dbcon.createStatement();
        rs = st.executeQuery("SELECT * from Login where cod_barra = " + TxtUser.getText());
        rs.first();
        
       if(rs.first()){
             JOptionPane.showMessageDialog(null,"Bem-Vindo");
          lo.setNivel_acesso(rs.getString("nivel_acesso"));
          
           
           MenuGUI Mengui = new MenuGUI();
           Mengui.setVisible(true);
          this.dispose();
          String nivelAcesso = rs.getString("nivel_acesso");
         Mengui.PegaDadosNivelAcesso(nivelAcesso);
          
        }
        else {
            JOptionPane.showMessageDialog(null,"Usuario não cadastrado");
        }
    } 
      catch (Exception ex){
          JOptionPane.showMessageDialog(null,"203 - Erro ao Exibir  Menu Principal:"+ex);
      }   
        }     
    }//GEN-LAST:event_TxtUserKeyPressed
          
    private void TxtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUserKeyReleased
       
    }//GEN-LAST:event_TxtUserKeyReleased

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
       
            
    }//GEN-LAST:event_TxtUserActionPerformed

    private void TxtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtUserKeyTyped
    
    }//GEN-LAST:event_TxtUserKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
     try {              
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());   
                 } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(LoginGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbNivelAcesso;
    private javax.swing.JPasswordField TxtSenha;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JButton btnEntra;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
