/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;
import DAO.ConexaoDAO;
import DAO.LoginDAO;
import Persistencia.Login;
import Persistencia.Mesa;
import com.mysql.jdbc.PreparedStatement;
import java.awt.GraphicsEnvironment;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Timer;
/**
 *
 * @author victor
 */
public class MenuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MenuGUI
     */
    ClienteGUI CliGUI = new ClienteGUI();
    FuncionarioGUI FunGUI = new FuncionarioGUI();
   ProdutoGUI ProdGUI = new ProdutoGUI();
   PedidoGUI  PedGUI = new PedidoGUI();
    //RelatorioGUI RelGUI = new RelatorioGUI();
    LoginDAO LD = new LoginDAO();

    Date data = new Date ();
    SimpleDateFormat formatador = new SimpleDateFormat ("dd/MM/yyyy");

    int hh,mm,ss;
    Calendar hora;
    Timer timer;
   
    
    
            public void iniciaRelogio(){
        new Thread(){//instancia nova thread já implementando o método run()
        @Override
        public void run() {//sobrescreve o método run()
        while(0 == 0){//while para fazer o loop infinito
        GregorianCalendar gc = new GregorianCalendar();//novo gregorian calendar, onde temos a data atual
        int hora = gc.get(Calendar.HOUR_OF_DAY);//pega as horas
        int minuto = gc.get(Calendar.MINUTE);//pega os minutos
        int segundo = gc.get(Calendar.SECOND);//pega os segundos
        String horaString;//nova string horas
        String minString;//nova string minutos
        String segundoString;//nova string segundos
        if(hora < 10){//se hora for menor que 10 precisa colocar um 0 à esquerda
        horaString = "0"+hora;
        }else{
        horaString = ""+hora;
        }
        if(minuto < 10){//se minuto for menor que 10 precisa colocar um 0 à esquerda
        minString = "0"+minuto;
        }
        else{
                minString = ""+minuto;
        }
        if(segundo < 10){//se segundo for menor que 10 precisa colocar um 0 à esquerda
        segundoString = "0"+segundo;
        }
        else{
                segundoString = ""+segundo;
        }
        Lblhora.setText("Horas:"+horaString+":"+minString+":"+segundoString);//seta hora atual no label
      try{
        sleep(1000);//faz a thread entrar em estado de espera por 1000 milissegundos ou 1 segundo       
      }
        catch(Exception e){}

        }
       }
    }
        .start();//inicia a thread.
}
   
    
    
    
    
    public MenuGUI() {
       
    initComponents();
    this.setExtendedState(MAXIMIZED_BOTH);
        //jButton1.setIcon(new ImageIcon("Imagens/clock.png"));
        //jButton1.setBorder(null);
   
    iniciaRelogio();
    LblData.setText("Data:"+formatador.format(data));
    
   
   
   // LblHora.setText(formatador_time.format(new Date(System.currentTimeMillis())));
    
    try {
            InetAddress end = InetAddress.getLocalHost();
            String nome_pc = end.getHostName();
            String ip = end.getHostAddress();
            LblIp.setText("Nome computador:"+nome_pc+"  Endereço ip:"+ip);
            
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"Erro:"+e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LblData = new javax.swing.JLabel();
        LblIp = new javax.swing.JLabel();
        Lblhora = new javax.swing.JLabel();
        TxtUsuario = new javax.swing.JLabel();
        btnFuncionario = new javax.swing.JLabel();
        btnCliente = new javax.swing.JLabel();
        btnProduto = new javax.swing.JLabel();
        btnPedido = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Untitled-1.fw.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setLayout(null);

        LblData.setForeground(java.awt.Color.white);
        LblData.setText("jLabel5");
        jPanel1.add(LblData);
        LblData.setBounds(0, 0, 160, 30);

        LblIp.setForeground(java.awt.Color.white);
        LblIp.setText("jLabel5");
        jPanel1.add(LblIp);
        LblIp.setBounds(340, 0, 480, 30);

        Lblhora.setForeground(java.awt.Color.white);
        Lblhora.setText("jLabel5");
        jPanel1.add(Lblhora);
        Lblhora.setBounds(160, 0, 150, 30);

        TxtUsuario.setForeground(java.awt.Color.gray);
        TxtUsuario.setText("jLabel5");
        jPanel1.add(TxtUsuario);
        TxtUsuario.setBounds(840, -10, 190, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 720, 1470, 40);

        btnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7818_64x64.png"))); // NOI18N
        btnFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionarioMouseEntered(evt);
            }
        });
        getContentPane().add(btnFuncionario);
        btnFuncionario.setBounds(0, 220, 70, 70);

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11983_64x64.png"))); // NOI18N
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
        });
        getContentPane().add(btnCliente);
        btnCliente.setBounds(0, 140, 70, 70);

        btnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/product-icon.png"))); // NOI18N
        btnProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProdutoMouseEntered(evt);
            }
        });
        getContentPane().add(btnProduto);
        btnProduto.setBounds(0, 320, 90, 70);

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/girl-beauty-consultant-products-icon.png"))); // NOI18N
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPedidoMouseEntered(evt);
            }
        });
        getContentPane().add(btnPedido);
        btnPedido.setBounds(0, 410, 64, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logout-icon (1).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 510, 60, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Untitled-1.fw.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });
        jLabel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel4KeyPressed(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1130, 760);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/whaite.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(910, -150, 1790, 900);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/whaite.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(990, 647, 1640, 120);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 560, 49, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
         if ("Administrador".equals(TxtUsuario.getText())){ 
             CliGUI.setVisible(true);
             FunGUI.setVisible(false);
             ProdGUI.setVisible(false);
             PedGUI.setVisible(false);
//             RelGUI.setVisible(false);
         }
         if ("Gerente".equals(TxtUsuario.getText())){ 
             CliGUI.setVisible(true);
             FunGUI.setVisible(false);
             ProdGUI.setVisible(false);
             PedGUI.setVisible(false);
  //           RelGUI.setVisible(false);
         }
         else{
             
         }
       
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionarioMouseEntered
        if ("Administrador".equals(TxtUsuario.getText())){ 
        FunGUI.setVisible(true);
         CliGUI.setVisible(false);
         ProdGUI.setVisible(false);
         PedGUI.setVisible(false);
    //     RelGUI.setVisible(false);
        }
        else {
            
        }
        
    }//GEN-LAST:event_btnFuncionarioMouseEntered

    private void btnProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProdutoMouseEntered
         if ("Administrador".equals(TxtUsuario.getText())){ 
             CliGUI.setVisible(false);
             FunGUI.setVisible(false);
             ProdGUI.setVisible(true);
             PedGUI.setVisible(false);
        //     RelGUI.setVisible(false);
         }
         if ("Gerente".equals(TxtUsuario.getText())){ 
             CliGUI.setVisible(false);
             FunGUI.setVisible(false);
             ProdGUI.setVisible(true);
             PedGUI.setVisible(false);
      //       RelGUI.setVisible(false);
         }
        
    }//GEN-LAST:event_btnProdutoMouseEntered

    private void btnPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMouseEntered
        
        PedGUI.setVisible(true);
        ProdGUI.setVisible(false); 
        FunGUI.setVisible(false);
        CliGUI.setVisible(false);
       // RelGUI.setVisible(false);
       
        
    }//GEN-LAST:event_btnPedidoMouseEntered

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
       
    
        //RelGUI.setVisible(false);
        PedGUI.setVisible(false);
        
        ProdGUI.setVisible(false); 
        FunGUI.setVisible(false);
        CliGUI.setVisible(false);
       
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel4KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_F1){
         LoginGUI log = new LoginGUI();
         log.setVisible(true);
      }
    }//GEN-LAST:event_jLabel4KeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       LoginGUI log = new LoginGUI();
       log.setVisible(true);
          //  RelGUI.setVisible(false);
            // RelGUI.dispose();
        PedGUI.setVisible(false);
        PedGUI.dispose();
        ProdGUI.setVisible(false);
          ProdGUI.dispose();
        FunGUI.setVisible(false);
        FunGUI.dispose();
        CliGUI.setVisible(false);
        CliGUI.dispose();
       this.dispose();
       
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
                 
                MenuGUI menu = new MenuGUI();
    
                java.awt.GraphicsDevice [] device = GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices();
                device[0].setFullScreenWindow(menu);
            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblIp;
    private javax.swing.JLabel Lblhora;
    private javax.swing.JLabel TxtUsuario;
    private javax.swing.JLabel btnCliente;
    private javax.swing.JLabel btnFuncionario;
    private javax.swing.JLabel btnPedido;
    private javax.swing.JLabel btnProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

 public void PegaDadosNivelAcesso(String NivelAcesso) {
       TxtUsuario.setText(NivelAcesso);
    }
}
