/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Visão;

import Controlador.ControladorCliente;
import Controlador.ControladorProduto;
import DAO.ConexaoDAO;
import DAO.ProdutoDAO;
import Persistencia.Produto;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import mondrian.olap.Category;
import org.apache.hadoop.record.compiler.JFile;
import util.NomeLetrasGrande;

/**
 *
 * @author victor
 */
public class ProdutoGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoGUI
     */
        Produto prod = new Produto();
    ControladorProduto contr = new ControladorProduto();
    ConexaoDAO conn = new ConexaoDAO();
    ProdutoDAO CD = new ProdutoDAO();
      int longitudBytes;
        FileInputStream fis;
        JFileChooser se = new JFileChooser();
    public void ativaCampos (){
        TxtCat.enable(true);
       TxtPreco.enable(true);
        TxtDesc.enable(true);
    }
    public void limpaCampos(){
        TxtCod.setText(null);

        TxtDesc.setText(null);
       TxtPreco.setText(null);
    }
    
    public ProdutoGUI() {
        initComponents();
        TxtDesc.setDocument(new NomeLetrasGrande());
        TxtCat.enable(false);
         TxtPreco.enable(false);
        TxtDesc.enable(false);
        
        TabelaCarros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
          try {
        conn.conecta();
        ResultSet rs = contr.listaProduto();
        DefaultTableModel modelo =  CD.carregarTabela(rs);
        TabelaCarros.setModel(modelo);
        TabelaCarros.setSelectionBackground(Color.yellow);
        
        }
        catch (Exception ex){
            JOptionPane.showMessageDialog(null,"Erro:");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TxtCod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbm_filtra = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        TxtPesquisar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaCarros = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btnCadastra = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TxtCat = new javax.swing.JComboBox();
        TxtPreco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("true"), this, org.jdesktop.beansbinding.BeanProperty.create("undecorated"));
        bindingGroup.addBinding(binding);

        jPanel1.setLayout(null);

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 27, 53, 30);

        TxtCod.setEnabled(false);
        jPanel1.add(TxtCod);
        TxtCod.setBounds(70, 30, 72, 27);

        jLabel2.setText("Categoria:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 30, 72, 30);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Pesquisar produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setText("Filtra por:");

        cbm_filtra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Categoria" }));

        jLabel9.setText("=");

        TxtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPesquisarActionPerformed(evt);
            }
        });
        TxtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPesquisarKeyReleased(evt);
            }
        });

        TabelaCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaCarrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelaCarros);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbm_filtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TxtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 210, 679, 260);
        jPanel5.getAccessibleContext().setAccessibleName("Pesquisar produto:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton4.setText("Novo");
        jButton4.setMaximumSize(new java.awt.Dimension(75, 29));
        jButton4.setMinimumSize(new java.awt.Dimension(75, 29));
        jButton4.setPreferredSize(new java.awt.Dimension(75, 29));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 160, 75, 29);

        btnCadastra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/accept.png"))); // NOI18N
        btnCadastra.setText("Cadastrar");
        btnCadastra.setEnabled(false);
        btnCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastra);
        btnCadastra.setBounds(90, 160, 100, 29);

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/delete_page.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.setEnabled(false);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeletar);
        btnDeletar.setBounds(270, 160, 85, 29);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/refresh.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(190, 160, 80, 29);

        jLabel3.setText("Preço:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 30, 45, 30);
        jPanel1.add(TxtDesc);
        TxtDesc.setBounds(90, 70, 360, 80);

        jLabel4.setText("Descrição:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 73, 17);

        lblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(lblFoto);
        lblFoto.setBounds(520, 20, 180, 130);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(580, 160, 80, 29);

        TxtCat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comidas", "Bebidas", "Sobremesas" }));
        jPanel1.add(TxtCat);
        TxtCat.setBounds(220, 30, 120, 27);

        TxtPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0,00"))));
        jPanel1.add(TxtPreco);
        TxtPreco.setBounds(400, 30, 110, 27);

        jTabbedPane1.addTab("Manunteção", new javax.swing.ImageIcon(getClass().getResource("/Imagens/process.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        try {

            prod.setCodProduto(Integer.parseInt(TxtCod.getText()));
            if (TxtCat.getSelectedIndex()==0){
                prod.setCategoria("Comidas");
            }
            if (TxtCat.getSelectedIndex()==1){
                prod.setCategoria("Bebidas");
            }
            if (TxtCat.getSelectedIndex()==2){
                prod.setCategoria("Sobremesas");
            }
            
            prod.setDescrição(TxtDesc.getText());
            prod.setPreco(Float.parseFloat( TxtPreco.getText()));
       File arquivo = this.se.getSelectedFile();
               prod.setAquivo(arquivo);
            int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja alterar o registro");

            if (resposta == 0){
                
                contr.alterarProduto(prod,this.se);
                limpaCampos();
                lblFoto.setIcon(null);
                try {
                    conn.conecta();
                    ResultSet rs = contr.listaProduto();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                    
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao listar:"+ex);
                }

            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null,"Erro no dados:"+ ex);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        prod.setCodProduto(Integer.parseInt(TxtCod.getText()));

        int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja excluir");

        if (resposta == 0){
            contr.excluirProduto(prod);
            limpaCampos();
             lblFoto.setIcon(null);
            try {
                conn.conecta();
                ResultSet rs = contr.listaProduto();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaCarros.setModel(modelo);
                TabelaCarros.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnCadastraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraActionPerformed
        
    
        if ((TxtDesc.getText().isEmpty())||(TxtPreco.getText().isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Existem campos em branco");

        }

        else{

            try {
                
                if (TxtCat.getSelectedIndex()==0){
                prod.setCategoria("Comidas");
            }
            if (TxtCat.getSelectedIndex()==1){
                prod.setCategoria("Bebidas");
            }
            if (TxtCat.getSelectedIndex()==2){
                prod.setCategoria("Sobremesas");
            }
            prod.setDescrição(TxtDesc.getText());
            prod.setPreco(Float.parseFloat(TxtPreco.getText()));

                int resposta =  JOptionPane.showConfirmDialog(null,"Você realmente deseja cadastra");
                      File arquivo = this.se.getSelectedFile();
               prod.setAquivo(arquivo);
                if (resposta == 0){
                    contr.incluirProduto(prod,this.se);
                    limpaCampos();
                    lblFoto.setIcon(null);
                    conn.conecta();

                    ResultSet rs = contr.listaProduto();
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);

                }

            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro No banco:"+ex);

            }

            // JOptionPane.showMessageDialog(null, "Modelo"+ca.getModelo()+"\n Nome:"+ca.getNome()+"\n Ano:"+ca.getAno()+"\n Cor:"+ca.getCor()+"\n Valor:"+ca.getValor()+"\n Pacote:"+ca.getPacote());

        }
    }//GEN-LAST:event_btnCadastraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  btnCadastra.setEnabled(true);
       btnAlterar.setEnabled(false);
       btnDeletar.setEnabled(false);
        ativaCampos();
        limpaCampos();
        lblFoto.setIcon(null);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void TabelaCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaCarrosMouseClicked
        try{
            int linha = TabelaCarros.getSelectedRow();
            //JOptionPane.showMessageDialog(null,"Linhas:"+ linha);
            Object objCodigo = TabelaCarros.getValueAt(linha, 0);
            Object objDesc = TabelaCarros.getValueAt(linha, 1);
            Object objcat = TabelaCarros.getValueAt(linha, 2);
            Object objpreco = TabelaCarros.getValueAt(linha, 3);
              ativaCampos();
       
              
       btnCadastra.setEnabled(false);
       btnAlterar.setEnabled(true);
       btnDeletar.setEnabled(true);
             
            TxtCod.setText(objCodigo.toString());
            TxtCat.setSelectedItem(objcat);
            TxtDesc.setText(objDesc.toString());
           TxtPreco.setText(objpreco.toString());
           prod.setCodProduto(Integer.parseInt(TxtCod.getText()));
           ImageIcon foto = CD.getFoto(prod);
           
           if (foto!=null){
               lblFoto.setIcon(CD.getFoto(prod));
                
               
           }
           else {
               lblFoto.setIcon(CD.getFoto(prod));
           }
          lblFoto.updateUI();
           
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null,"Erro ao carregar os dados"+e.getMessage());
        }
    }//GEN-LAST:event_TabelaCarrosMouseClicked

    private void TxtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyReleased
        if(TxtPesquisar.getText().isEmpty()){
            try {
                conn.conecta();
                ResultSet rs = contr.listaProduto();
                DefaultTableModel modelo =  CD.carregarTabela(rs);
                TabelaCarros.setModel(modelo);
                TabelaCarros.setSelectionBackground(Color.yellow);
            }
            catch (Exception ex){
                JOptionPane.showMessageDialog(null,"Erro:");
            }
        }

        else{
            if (cbm_filtra.getSelectedIndex()==0){
                try {
                    prod.setCodProduto(Integer.parseInt(TxtPesquisar.getText()));
                    conn.conecta();
                    ResultSet rs = contr.buscarCodigoProduto(prod);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao buscar dados:"+ex.getMessage());
                }
            }

            if (cbm_filtra.getSelectedIndex()==1){
                try {
                    prod.setCategoria((TxtPesquisar.getText()));
                    conn.conecta();
                    ResultSet rs = contr.buscarCategoriaProduto(prod);
                    DefaultTableModel modelo =  CD.carregarTabela(rs);
                    TabelaCarros.setModel(modelo);
                    TabelaCarros.setSelectionBackground(Color.yellow);
                }
                catch (Exception ex){
                    JOptionPane.showMessageDialog(null,"Erro ao buscar dados:"+ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_TxtPesquisarKeyReleased

    private void TxtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPesquisarKeyPressed

    }//GEN-LAST:event_TxtPesquisarKeyPressed

    private void TxtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPesquisarActionPerformed

    }//GEN-LAST:event_TxtPesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        
        this.se.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int  estado = this.se.showOpenDialog(null);
        if (estado == JFileChooser.APPROVE_OPTION){
            try {
          
            this.fis =  new FileInputStream(this.se.getSelectedFile());
            this.longitudBytes = (int) this.se.getSelectedFile().length();
           
            Image icon = ImageIO.read(this.se.getSelectedFile()).getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_DEFAULT);
            lblFoto.setIcon(new ImageIcon(icon));
            lblFoto.updateUI();
            }
            catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erro ao carregar foto :"+ex);
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {              
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());   
                 } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(ProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(ProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(ProdutoGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaCarros;
    private javax.swing.JComboBox TxtCat;
    private javax.swing.JTextField TxtCod;
    private javax.swing.JTextField TxtDesc;
    private javax.swing.JTextField TxtPesquisar;
    private javax.swing.JFormattedTextField TxtPreco;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastra;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JComboBox cbm_filtra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblFoto;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
